### ISSUE TITLE
resources 2

### ISSUE THREAD

**Issue by smarcet** [OpenStackweb/navigation-widget#3]
https://github.com/OpenStackweb/navigation-widget/blob/a7b0f7d3eda72deb921dfbe13ea8a1552523bbc7/src/components/popup/popup.js#L31

@tomrndom lets do this a prop type with a prod default value set to current one
regards

**Comment by tomrndom** [comment]
@smarcet this is fixed on this commit 85f6599958fa7c22490d5ccae85604a1a1dd1927. Regards
