### ISSUE TITLE
resource 3

### ISSUE THREAD

**Issue by smarcet** [OpenStackweb/navigation-widget#4]
https://github.com/OpenStackweb/navigation-widget/blob/a7b0f7d3eda72deb921dfbe13ea8a1552523bbc7/src/components/popup/popup.js#L46

lets create a prop type with a default value to current one

regards

**Comment by tomrndom** [comment]
@smarcet this is fixed on this commit 85f6599958fa7c22490d5ccae85604a1a1dd1927. Regards
