### ISSUE TITLE
missing anchor 1

### ISSUE THREAD

**Issue by smarcet** [OpenStackweb/navigation-widget#5]
https://github.com/OpenStackweb/navigation-widget/blob/a7b0f7d3eda72deb921dfbe13ea8a1552523bbc7/src/components/project/project.js#L27

project name should be enclosed on an anchor with href set to project. site_url

**Comment by tomrndom** [comment]
@smarcet this is fixed on this commit 85f6599958fa7c22490d5ccae85604a1a1dd1927. Regards
